-- ============================================================================
-- V16: catálogo efficient e inefficient — 12 tips × 5 dominios por nivel (120 filas)
-- Dominios: climate, lighting, equipment, habits, tech
-- ============================================================================

INSERT INTO recommendation_catalog (tip_key, title, type, nivel, category_key) VALUES

-- Climatización × efficient
('CLIMATE_EFF_01', 'Mantener termostato en 25°C cuando el clima lo permita', 'INFO', 'efficient', 'climate'),
('CLIMATE_EFF_02', 'Usar modo ventilación sin compresor en días templados', 'INFO', 'efficient', 'climate'),
('CLIMATE_EFF_03', 'Aprovechar brisa nocturna para refrescar antes del amanecer', 'INFO', 'efficient', 'climate'),
('CLIMATE_EFF_04', 'Revisar calendario estacional del equipo de climatización', 'OPORTUNIDAD', 'efficient', 'climate'),
('CLIMATE_EFF_05', 'Mantener filtros limpios según plan de mantenimiento preventivo', 'OPORTUNIDAD', 'efficient', 'climate'),
('CLIMATE_EFF_06', 'Usar cortinas térmicas solo cuando aporten valor adicional', 'INFO', 'efficient', 'climate'),
('CLIMATE_EFF_07', 'Evitar sobreenfriar espacios ya confortables', 'INFO', 'efficient', 'climate'),
('CLIMATE_EFF_08', 'Registrar consumo mensual de climatización para detectar desvíos', 'OPORTUNIDAD', 'efficient', 'climate'),
('CLIMATE_EFF_09', 'Cerrar puertas interiores para zonificar sin exceso de equipos', 'INFO', 'efficient', 'climate'),
('CLIMATE_EFF_10', 'Preferir ventilador de bajo consumo antes que bajar más la temperatura', 'INFO', 'efficient', 'climate'),
('CLIMATE_EFF_11', 'Verificar que el termostato no esté expuesto a sol directo', 'OPORTUNIDAD', 'efficient', 'climate'),
('CLIMATE_EFF_12', 'Compartir buenas prácticas de climatización con otros ocupantes', 'INFO', 'efficient', 'climate'),

-- Iluminación × efficient
('LIGHTING_EFF_01', 'Apagar luces en zonas con suficiente luz natural', 'INFO', 'efficient', 'lighting'),
('LIGHTING_EFF_02', 'Usar iluminación puntual en lugar de iluminar toda la habitación', 'INFO', 'efficient', 'lighting'),
('LIGHTING_EFF_03', 'Mantener focos LED en buen estado sin parpadeo', 'OPORTUNIDAD', 'efficient', 'lighting'),
('LIGHTING_EFF_04', 'Ajustar intensidad al mínimo confortable en cada espacio', 'INFO', 'efficient', 'lighting'),
('LIGHTING_EFF_05', 'Revisar que sensores de presencia estén bien calibrados', 'OPORTUNIDAD', 'efficient', 'lighting'),
('LIGHTING_EFF_06', 'Evitar luces nocturnas permanentes innecesarias', 'INFO', 'efficient', 'lighting'),
('LIGHTING_EFF_07', 'Limitar iluminación decorativa a horarios definidos', 'INFO', 'efficient', 'lighting'),
('LIGHTING_EFF_08', 'Preferir lámparas direccionables para evitar sobreiluminar', 'OPORTUNIDAD', 'efficient', 'lighting'),
('LIGHTING_EFF_09', 'Documentar layout de iluminación eficiente del hogar', 'INFO', 'efficient', 'lighting'),
('LIGHTING_EFF_10', 'Cambiar solo los focos que aún no son LED', 'OPORTUNIDAD', 'efficient', 'lighting'),
('LIGHTING_EFF_11', 'Usar temporizadores en exteriores con horario mínimo necesario', 'OPORTUNIDAD', 'efficient', 'lighting'),
('LIGHTING_EFF_12', 'Medir consumo de iluminación tras cambios para validar ahorro', 'INFO', 'efficient', 'lighting'),

-- Equipamiento × efficient
('EQUIPMENT_EFF_01', 'Usar programas eco en todos los ciclos compatibles', 'INFO', 'efficient', 'equipment'),
('EQUIPMENT_EFF_02', 'Mantener electrodomésticos en modo eficiente de fábrica', 'INFO', 'efficient', 'equipment'),
('EQUIPMENT_EFF_03', 'Desconectar equipos secundarios fuera de temporada', 'OPORTUNIDAD', 'efficient', 'equipment'),
('EQUIPMENT_EFF_04', 'Revisar manual de eficiencia de cada electrodoméstico principal', 'INFO', 'efficient', 'equipment'),
('EQUIPMENT_EFF_05', 'Evitar standby innecesario en equipos ya eficientes', 'OPORTUNIDAD', 'efficient', 'equipment'),
('EQUIPMENT_EFF_06', 'Usar olla a presión eléctrica para reducir tiempo de cocción', 'INFO', 'efficient', 'equipment'),
('EQUIPMENT_EFF_07', 'Mantener refrigerador entre 3°C y 5°C sin sobre-enfriar', 'INFO', 'efficient', 'equipment'),
('EQUIPMENT_EFF_08', 'Planificar una carga semanal de lavado consolidada', 'OPORTUNIDAD', 'efficient', 'equipment'),
('EQUIPMENT_EFF_09', 'Preferir secado al aire cuando el clima lo permita', 'INFO', 'efficient', 'equipment'),
('EQUIPMENT_EFF_10', 'Etiquetar equipos por consumo relativo en el hogar', 'INFO', 'efficient', 'equipment'),
('EQUIPMENT_EFF_11', 'Revisar sellos de electrodomésticos una vez por trimestre', 'OPORTUNIDAD', 'efficient', 'equipment'),
('EQUIPMENT_EFF_12', 'Renovar equipos solo cuando la eficiencia lo justifique', 'INFO', 'efficient', 'equipment'),

-- Hábitos × efficient
('HABITS_EFF_01', 'Mantener rutina de apagado al salir de cada habitación', 'INFO', 'efficient', 'habits'),
('HABITS_EFF_02', 'Limitar duchas a lo necesario con cierre rápido del grifo', 'INFO', 'efficient', 'habits'),
('HABITS_EFF_03', 'Usar horario valle para cargas programables habituales', 'OPORTUNIDAD', 'efficient', 'habits'),
('HABITS_EFF_04', 'Revisar consumo semanal en la app como hábito fijo', 'INFO', 'efficient', 'habits'),
('HABITS_EFF_05', 'Coordinar uso de equipos compartidos para evitar duplicidad', 'OPORTUNIDAD', 'efficient', 'habits'),
('HABITS_EFF_06', 'Evitar precalentar espacios que ya están confortables', 'INFO', 'efficient', 'habits'),
('HABITS_EFF_07', 'Cerrar persianas en verano antes de la radiación máxima', 'INFO', 'efficient', 'habits'),
('HABITS_EFF_08', 'Preferir actividades manuales de bajo consumo cuando sea viable', 'INFO', 'efficient', 'habits'),
('HABITS_EFF_09', 'Establecer meta de reducción incremental del 2% mensual', 'OPORTUNIDAD', 'efficient', 'habits'),
('HABITS_EFF_10', 'Apagar tiras LED decorativas al dormir', 'INFO', 'efficient', 'habits'),
('HABITS_EFF_11', 'Usar regla de un equipo pesado encendido a la vez', 'INFO', 'efficient', 'habits'),
('HABITS_EFF_12', 'Celebrar y documentar hitos de ahorro con el hogar', 'INFO', 'efficient', 'habits'),

-- Tecnología × efficient
('TECH_EFF_01', 'Automatizar apagado nocturno de periféricos de cómputo', 'OPORTUNIDAD', 'efficient', 'tech'),
('TECH_EFF_02', 'Usar medidor inteligente para confirmar ausencia de standby', 'INFO', 'efficient', 'tech'),
('TECH_EFF_03', 'Mantener firmware actualizado en dispositivos conectados', 'OPORTUNIDAD', 'efficient', 'tech'),
('TECH_EFF_04', 'Configurar alertas de consumo anómalo en apps compatibles', 'INFO', 'efficient', 'tech'),
('TECH_EFF_05', 'Preferir Wi-Fi programable para reducir equipos activos', 'OPORTUNIDAD', 'efficient', 'tech'),
('TECH_EFF_06', 'Desactivar LEDs indicadores innecesarios cuando sea posible', 'INFO', 'efficient', 'tech'),
('TECH_EFF_07', 'Usar regletas con horario para cargadores compartidos', 'OPORTUNIDAD', 'efficient', 'tech'),
('TECH_EFF_08', 'Auditar dispositivos IoT y retirar los que no aporten valor', 'OPORTUNIDAD', 'efficient', 'tech'),
('TECH_EFF_09', 'Sincronizar escenas domóticas con presencia real en el hogar', 'INFO', 'efficient', 'tech'),
('TECH_EFF_10', 'Medir consumo de rack de red y optimizar horarios', 'OPORTUNIDAD', 'efficient', 'tech'),
('TECH_EFF_11', 'Elegir monitores eficientes al ampliar puestos de trabajo', 'INFO', 'efficient', 'tech'),
('TECH_EFF_12', 'Exportar reportes mensuales de consumo conectado', 'INFO', 'efficient', 'tech'),

-- Climatización × inefficient
('CLIMATE_INEFF_01', 'Revisar urgentemente equipos de climatización con consumo creciente', 'ALERTA', 'inefficient', 'climate'),
('CLIMATE_INEFF_02', 'Sustituir unidades viejas con bajo SEER por modelos eficientes', 'ALERTA', 'inefficient', 'climate'),
('CLIMATE_INEFF_03', 'Priorizar aislamiento en habitaciones con mayor pérdida térmica', 'OPORTUNIDAD', 'inefficient', 'climate'),
('CLIMATE_INEFF_04', 'Limitar horas de AA a bloques estrictos en horario pico', 'ALERTA', 'inefficient', 'climate'),
('CLIMATE_INEFF_05', 'Detectar y sellar filtraciones de aire en ventanas prioritarias', 'OPORTUNIDAD', 'inefficient', 'climate'),
('CLIMATE_INEFF_06', 'Evitar climatizar zonas abiertas o mal cerradas', 'ALERTA', 'inefficient', 'climate'),
('CLIMATE_INEFF_07', 'Usar termostato programable con límites máximos de uso diario', 'OPORTUNIDAD', 'inefficient', 'climate'),
('CLIMATE_INEFF_08', 'Solicitar mantenimiento profesional si el consumo no baja', 'ALERTA', 'inefficient', 'climate'),
('CLIMATE_INEFF_09', 'Reducir temperatura de consigna un grado por semana hasta 24°C', 'OPORTUNIDAD', 'inefficient', 'climate'),
('CLIMATE_INEFF_10', 'Instalar sensor puerta-ventana para apagar AA al ventilar', 'OPORTUNIDAD', 'inefficient', 'climate'),
('CLIMATE_INEFF_11', 'Evitar usar AA simultáneamente con calefacción eléctrica', 'ALERTA', 'inefficient', 'climate'),
('CLIMATE_INEFF_12', 'Planificar inversión en doble vidriado en la próxima renovación', 'OPORTUNIDAD', 'inefficient', 'climate'),

-- Iluminación × inefficient
('LIGHTING_INEFF_01', 'Sustituir de inmediato todas las lámparas incandescentes o halógenas', 'ALERTA', 'inefficient', 'lighting'),
('LIGHTING_INEFF_02', 'Eliminar iluminación exterior encendida todo el día sin necesidad', 'ALERTA', 'inefficient', 'lighting'),
('LIGHTING_INEFF_03', 'Instalar sensores de movimiento en todas las zonas de tránsito', 'OPORTUNIDAD', 'inefficient', 'lighting'),
('LIGHTING_INEFF_04', 'Reducir cantidad de puntos de luz activos en áreas amplias', 'OPORTUNIDAD', 'inefficient', 'lighting'),
('LIGHTING_INEFF_05', 'Apagar iluminación decorativa hasta completar migración LED', 'OPORTUNIDAD', 'inefficient', 'lighting'),
('LIGHTING_INEFF_06', 'Revisar balastos viejos que generan consumo excesivo', 'ALERTA', 'inefficient', 'lighting'),
('LIGHTING_INEFF_07', 'Priorizar iluminación LED en cocina y baños de alto uso', 'OPORTUNIDAD', 'inefficient', 'lighting'),
('LIGHTING_INEFF_08', 'Usar una sola fuente de luz central en lugar de múltiples lámparas', 'OPORTUNIDAD', 'inefficient', 'lighting'),
('LIGHTING_INEFF_09', 'Medir antes y después del cambio masivo a LED', 'INFO', 'inefficient', 'lighting'),
('LIGHTING_INEFF_10', 'Desactivar letreros o carteles luminosos no esenciales', 'OPORTUNIDAD', 'inefficient', 'lighting'),
('LIGHTING_INEFF_11', 'Programar apagado total de luces exteriores en horario diurno', 'OPORTUNIDAD', 'inefficient', 'lighting'),
('LIGHTING_INEFF_12', 'Consultar subsidio o programa local de eficiencia lumínica', 'INFO', 'inefficient', 'lighting'),

-- Equipamiento × inefficient
('EQUIPMENT_INEFF_01', 'Reemplazar electrodomésticos de más de diez años con etiqueta A o superior', 'ALERTA', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_02', 'Evitar usar secadora en días soleados; usar tendedero', 'OPORTUNIDAD', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_03', 'No operar lavadora, horno y microondas al mismo tiempo', 'ALERTA', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_04', 'Revisar circuito dedicado para equipos de alto consumo', 'ALERTA', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_05', 'Desconectar segunda heladera o freezer si no es indispensable', 'OPORTUNIDAD', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_06', 'Usar timer en termotanque para limitar horas de calentamiento', 'OPORTUNIDAD', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_07', 'Evitar plancha y aspiradora en horario pico eléctrico', 'OPORTUNIDAD', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_08', 'Consolidar cocción en un solo bloque diario', 'OPORTUNIDAD', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_09', 'Retirar equipos obsoletos que permanecen conectados', 'OPORTUNIDAD', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_10', 'Priorizar reparación de sellos en refrigeración antes de verano', 'ALERTA', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_11', 'Evaluar arrendamiento de equipos eficientes vs reparar viejos', 'INFO', 'inefficient', 'equipment'),
('EQUIPMENT_INEFF_12', 'Instalar protector de voltaje en equipos críticos para evitar daños', 'OPORTUNIDAD', 'inefficient', 'equipment'),

-- Hábitos × inefficient
('HABITS_INEFF_01', 'Reducir duchas a cinco minutos como máximo inmediato', 'ALERTA', 'inefficient', 'habits'),
('HABITS_INEFF_02', 'Desplazar lavado, plancha y cocina intensa fuera del pico', 'OPORTUNIDAD', 'inefficient', 'habits'),
('HABITS_INEFF_03', 'Apagar todo equipo no esencial al salir de casa', 'ALERTA', 'inefficient', 'habits'),
('HABITS_INEFF_04', 'Establecer tope diario de horas de entretenimiento eléctrico', 'OPORTUNIDAD', 'inefficient', 'habits'),
('HABITS_INEFF_05', 'Revisar factura semanal y fijar meta de reducción del 15%', 'OPORTUNIDAD', 'inefficient', 'habits'),
('HABITS_INEFF_06', 'Limitar cantidad de dispositivos cargando simultáneamente', 'OPORTUNIDAD', 'inefficient', 'habits'),
('HABITS_INEFF_07', 'Evitar dormir con AA a temperatura muy baja', 'ALERTA', 'inefficient', 'habits'),
('HABITS_INEFF_08', 'Involucrar a todos con checklist diario de apagado', 'OPORTUNIDAD', 'inefficient', 'habits'),
('HABITS_INEFF_09', 'Desconectar equipos que permanecen encendidos 24/7 sin necesidad', 'ALERTA', 'inefficient', 'habits'),
('HABITS_INEFF_10', 'Usar ventilación natural cuando la calidad del aire lo permita', 'OPORTUNIDAD', 'inefficient', 'habits'),
('HABITS_INEFF_11', 'Priorizar una auditoría energética domiciliaria profesional', 'INFO', 'inefficient', 'habits'),
('HABITS_INEFF_12', 'Registrar hábitos diarios que más impactan la factura', 'INFO', 'inefficient', 'habits'),

-- Tecnología × inefficient
('TECH_INEFF_01', 'Instalar medidor de enchufe en los cinco equipos más sospechosos', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_02', 'Configurar smart plugs para apagar standby masivo nocturno', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_03', 'Retirar dispositivos IoT duplicados o sin uso', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_04', 'Migrar entretenimiento a una sola regleta maestra con apagado total', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_05', 'Desactivar servidores caseros o NAS fuera de horario laboral', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_06', 'Sustituir cargadores genéricos por versiones eficientes certificadas', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_07', 'Limitar cantidad de hubs inteligentes encendidos permanentemente', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_08', 'Activar modo ahorro agresivo en todos los equipos compatibles', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_09', 'Auditar apps que mantienen hardware activo innecesariamente', 'ALERTA', 'inefficient', 'tech'),
('TECH_INEFF_10', 'Consolidar cargadores en estación única con timer', 'OPORTUNIDAD', 'inefficient', 'tech'),
('TECH_INEFF_11', 'Planificar upgrade a domótica con métricas de retorno de inversión', 'INFO', 'inefficient', 'tech'),
('TECH_INEFF_12', 'Eliminar dispositivos fantasma conectados a la red doméstica', 'OPORTUNIDAD', 'inefficient', 'tech');
